project:
  type: website
  preview:
    port: 7777

website:
  title: "Dmitri's Website"
  site-url: https://dmitrische.github.io/
  image: images/mug.jpg
  page-navigation: false
  reader-mode: false
  navbar:
    title: false
    pinned: true
    left: 
      - icon: house
        href: index.qmd
        text: "Home"
      - icon: file-person-fill
        text: CV
        href: assets/DmitriCV.pdf
      - icon: wrench-adjustable
        href: skills/skills.qmd
        text: Skills
      - icon: folder2-open #journal-richtext
        text: Portfolio
        href: work/index.qmd
      - icon: pencil-square #newspaper
        text: Blog
        href: blog/index.qmd
    right:
      - icon: code-slash
        href: https://github.com/dmitrische/dmitrische.github.io

format:
  html:
    theme: simplex
    #css: styles.css
    toc: false
    smooth-scroll: true
    format:
      html:
        link-external-icon: true
        link-external-newwindow: true
        #link-external-filter: '^(?:http:|https:)\/\/forbo7\.github\.io\/'

execute:
  freeze: auto

## Could separate out directives into separate .yml files
## and link to them using the metadata-files keyword, e.g.
#metadata-files:
#  - _website.yml
#  - _format.yml
## But for now I've decided to keep all the directives here.